ARDUINO_LIB_PATH=/usr/share/arduino/libraries
USER_LIB_PATH=../../../libraries
ARDUINO_LIBS  = TFT SPI I2C OneWire ChronodotI2C MPL3115A2 DHT DS18
ARDUINO_DIR   = /usr/share/arduino
ARDMK_DIR     = /usr/share/arduino
AVR_TOOLS_DIR = /usr
AVRDUDE_CONF  = /usr/share/arduino/hardware/tools/avrdude.conf
BOARD_TAG     = uno
include $(ARDMK_DIR)/Arduino.mk
